repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/trufflesecurity/truffleHog
    rev: v3.25.4
    hooks:
      - id: trufflehog

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.22.0
    hooks:
      - id: semgrep
        args: ['--config', 'p/ci']
