name: Bandit Scan

on:
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    name: Run Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . --severity-level high --confidence-level high
