name: TruffleHog Scan

on:
  pull_request:
    branches:
      - master

jobs:
  trufflehog_scan:
    name: Run TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog-actions-scan@v3
        with:
          scan: 'filesystem'
          github_token: ${{ secrets.GITHUB_TOKEN }}
