name: TruffleHog Scan

on:
  pull_request:
    branches:
      - master

jobs:
  trufflehog_scan:
    name: Run TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.82.2
        
