name: Security Scans

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  security_scans:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies and security tools
      - name: Install Dependencies and Tools
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety truffleHog semgrep

      # Run Bandit for SAST
      - name: Run Bandit (SAST)
        run: |
          bandit -r . --severity-level high --confidence-level high
        continue-on-error: false

      # Run Safety for SCA
      - name: Run Safety (SCA)
        run: |
          safety check -r requirements.txt --full-report
        continue-on-error: false

      # Run Semgrep for SAST
      - name: Run Semgrep (SAST)
        run: |
          semgrep --config p/ci .
        continue-on-error: false

      # Run TruffleHog for Secret Scanning
      - name: Run TruffleHog (Secret Scanning)
        run: |
          trufflehog filesystem --directory=.
        continue-on-error: false
